- name: Install ca-certificates
  apt:
    name: ca-certificates

- name: Install curl
  apt:
    name: curl
    
- name: Install apt-transport-https
  apt:
    name: apt-transport-https

- name: Install lsb-release
  apt:
    name: lsb-release

- name: Install gnupg
  apt:
    name: gnupg

- name: Download the Microsoft signing key for repo
  shell: >
    curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

- name: Update repo and install azure-cli
  apt:
    name: azure-cli
    update_cache: yes
    state: present



