- name: Check if gh repo file exists on machine
  stat:
    path: /etc/apt/sources.list.d/github-cli.list
  register: gh_repo_check

- name: Add gh repo if not there
  shell: >
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  when: not gh_repo_check.stat.exists

- name: Install github cli
  apt:
    name: gh
  when: gh_repo_check.stat.exists
